Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -6,19 +6,21 @@ on:
 jobs:
   create:
     runs-on: ubuntu-latest
-    if: github.event.created
     steps:
-      - run: echo Created!
+      - name: created
+        run: " [[ ${{ github.event.created }} == 'false' ]] || exit 0;"
+      - if: steps.created.conclusion == 'failure'
+        run: echo "failure";
+      - if: steps.created.conclusion == 'success'
+        run: echo "success";
   build-backend:
     runs-on: ubuntu-latest
     needs: create
-    if: always() && (needs.create.result == 'skipped' || needs.create.result == 'success')
     steps:
       - run: echo Build backend
   build-frontend:
     runs-on: ubuntu-latest
     needs: create
-    if: always() && (needs.create.result == 'skipped' || needs.create.result == 'success')
     strategy:
       matrix:
         include:
